name: Lint & prettier checks

on:
  pull_request:
    branches:
      - main
      - release/**
  push:
    branches:
      - main
      - release/**
    tags:
      - v*

jobs:
  lint:
    name: ESLint & prettier
    runs-on: hl-contr-lin-md

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24.12.0

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .

      - name: Run prettier check
        run: npx prettier test --check
